Repository malviguys/frontendcli, pull requests merged in 2021-12, with the labels that each got.

#5 Dev
  .gitignore
  domain_objects/cost.py
  requirement.txt
  tests/__init__.py
  tests/domain_objects/test_cost.py
Labels: frontend, development

#6 Update requirement and Added menu class
  domain_objects/lesson.py
  domain_objects/user.py
  menu/__init__.py
  menu/menu.py
  requirement.txt
Labels: frontend, development, TUI

#7 Lesson validation, str and testing
  domain_objects/lesson.py
  domain_objects/user.py
  tests/domain_objects/test_lesson.py
Labels: frontend, development, TUI

#8 Menu updates into branch for testing the menu
  core/app.py
  domain_objects/lesson.py
  domain_objects/user.py
  menu/__init__.py
  menu/handler.py
  menu/menu.py
  requirement.txt
  tests/domain_objects/test_cost.py
  tests/domain_objects/test_lesson.py
  tests/menu/__init__.py
  tests/menu/test_description.py
  tests/menu/test_entry.py
  tests/menu/test_key.py
  tests/menu/test_menu.py
Labels: frontend, development, testing, TUI

#10 Menu fixes and tests
  core/__init__.py
  core/app.py
  domain_objects/lesson.py
  domain_objects/user.py
  menu/handler.py
  menu/menu.py
  requirement.txt
  tests/core/__init__.py
  tests/core/test_app.py
  tests/domain_objects/test_cost.py
  tests/domain_objects/test_lesson.py
  tests/domain_objects/test_user.py
  tests/menu/test_description.py
  tests/menu/test_entry.py
  tests/menu/test_handler.py
  tests/menu/test_key.py
  tests/menu/test_menu.py
  validation/dataclasses.py
  validation/regex.py
Labels: frontend, development, testing, TUI

#11 Menu interface
  domain_objects/user.py
  menu/handler.py
Labels: frontend, development, TUI

#13 Test menu
  core/app.py
  domain_objects/lesson.py
  domain_objects/user.py
  menu/handler.py
  tests/core/test_app.py
  tests/menu/test_handler.py
Labels: frontend, development, testing, TUI

#14 Menu interface into Test menu
  core/app.py
  domain_objects/user.py
  menu/handler.py
  menu/menu.py
Labels: frontend, development, testing, TUI

#15 Finished menu and tests into main
  __init__.py
  core/__init__.py
  core/app.py
  core/domain_objects/__init__.py
  core/domain_objects/cost.py
  core/domain_objects/lesson.py
  core/domain_objects/user.py
  core/menu/__init__.py
  core/menu/handler.py
  core/menu/menu.py
  core/validation/__init__.py
  core/validation/dataclasses.py
  core/validation/regex.py
  domain_objects/lesson.py
  domain_objects/user.py
  requirement.txt
  tests/core/__init__.py
  tests/core/test_app.py
  tests/domain_objects/test_cost.py
  tests/domain_objects/test_lesson.py
  tests/domain_objects/test_user.py
  tests/menu/test_description.py
  tests/menu/test_entry.py
  tests/menu/test_handler.py
  tests/menu/test_key.py
  tests/menu/test_menu.py
Labels: frontend, development, testing, TUI
